const Ziggy = {
    url: 'http:\/\/localhost',
    port: null,
    defaults: {},
    routes: {
        home: { uri: '\/', methods: ['GET', 'HEAD'] },
        dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
        'profile.edit': { uri: 'settings\/profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'settings\/profile', methods: ['PATCH'] },
        'profile.password': { uri: 'profile\/password', methods: ['PATCH'] },
        'profile.destroy': { uri: 'settings\/profile', methods: ['DELETE'] },
        'subscriptions.index': { uri: 'subscriptions', methods: ['GET', 'HEAD'] },
        'subscriptions.create': { uri: 'subscriptions\/create', methods: ['GET', 'HEAD'] },
        'subscriptions.store': { uri: 'subscriptions', methods: ['POST'] },
        'subscriptions.show': {
            uri: 'subscriptions\/{subscription}',
            methods: ['GET', 'HEAD'],
            parameters: ['subscription'],
            bindings: { subscription: 'id' },
        },
        'subscriptions.edit': {
            uri: 'subscriptions\/{subscription}\/edit',
            methods: ['GET', 'HEAD'],
            parameters: ['subscription'],
            bindings: { subscription: 'id' },
        },
        'subscriptions.update': {
            uri: 'subscriptions\/{subscription}',
            methods: ['PUT', 'PATCH'],
            parameters: ['subscription'],
            bindings: { subscription: 'id' },
        },
        'subscriptions.destroy': {
            uri: 'subscriptions\/{subscription}',
            methods: ['DELETE'],
            parameters: ['subscription'],
            bindings: { subscription: 'id' },
        },
        'subscriptions.mark-paid': {
            uri: 'subscriptions\/{subscription}\/mark-paid',
            methods: ['POST'],
            parameters: ['subscription'],
            bindings: { subscription: 'id' },
        },
        'categories.index': { uri: 'categories', methods: ['GET', 'HEAD'] },
        'categories.create': { uri: 'categories\/create', methods: ['GET', 'HEAD'] },
        'categories.store': { uri: 'categories', methods: ['POST'] },
        'categories.show': { uri: 'categories\/{category}', methods: ['GET', 'HEAD'], parameters: ['category'], bindings: { category: 'id' } },
        'categories.edit': { uri: 'categories\/{category}\/edit', methods: ['GET', 'HEAD'], parameters: ['category'], bindings: { category: 'id' } },
        'categories.update': { uri: 'categories\/{category}', methods: ['PUT', 'PATCH'], parameters: ['category'], bindings: { category: 'id' } },
        'categories.destroy': { uri: 'categories\/{category}', methods: ['DELETE'], parameters: ['category'], bindings: { category: 'id' } },
        'payment-methods.index': { uri: 'payment-methods', methods: ['GET', 'HEAD'] },
        'payment-methods.create': { uri: 'payment-methods\/create', methods: ['GET', 'HEAD'] },
        'payment-methods.store': { uri: 'payment-methods', methods: ['POST'] },
        'payment-methods.show': { uri: 'payment-methods\/{payment_method}', methods: ['GET', 'HEAD'], parameters: ['payment_method'] },
        'payment-methods.edit': { uri: 'payment-methods\/{payment_method}\/edit', methods: ['GET', 'HEAD'], parameters: ['payment_method'] },
        'payment-methods.update': { uri: 'payment-methods\/{payment_method}', methods: ['PUT', 'PATCH'], parameters: ['payment_method'] },
        'payment-methods.destroy': { uri: 'payment-methods\/{payment_method}', methods: ['DELETE'], parameters: ['payment_method'] },
        'payment-histories.index': { uri: 'payment-histories', methods: ['GET', 'HEAD'] },
        'payment-histories.show': { uri: 'payment-histories\/{payment_history}', methods: ['GET', 'HEAD'], parameters: ['payment_history'] },
        'settings.currencies.index': { uri: 'settings\/currencies', methods: ['GET', 'HEAD'] },
        'settings.currencies.update': { uri: 'settings\/currencies', methods: ['PATCH'] },
        'settings.currencies.store': { uri: 'settings\/currencies', methods: ['POST'] },
        'settings.currencies.destroy': {
            uri: 'settings\/currencies\/{currency}',
            methods: ['DELETE'],
            parameters: ['currency'],
            bindings: { currency: 'id' },
        },
        'test.subscription.edit': { uri: 'test\/subscription\/{id}\/edit', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'password.edit': { uri: 'settings\/password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'settings\/password', methods: ['PUT'] },
        appearance: { uri: 'settings\/appearance', methods: ['GET', 'HEAD'] },
        register: { uri: 'register', methods: ['GET', 'HEAD'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': { uri: 'verify-email\/{id}\/{hash}', methods: ['GET', 'HEAD'], parameters: ['id', 'hash'] },
        'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        logout: { uri: 'logout', methods: ['POST'] },
        'storage.local': { uri: 'storage\/{path}', methods: ['GET', 'HEAD'], wheres: { path: '.*' }, parameters: ['path'] },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
